In [107]:
import requests
import pandas as pd
from datetime import datetime, timedelta

In [108]:
# API Key for OpenWeatherMap
api_key = "Your_API_Key"

# List of cities for weather data
cities = ["London, United Kingdom",    
          "Paris, France",    
          "New York, United States",    
          "Tokyo, Japan",    
          "Beijing, China",    
          "Istanbul, Turkey",    
          "Moscow, Russia",    
          "Berlin, Germany",    
          "Bangkok, Thailand",    
          "Seoul, South Korea",   
          "Mumbai, India",   
          "Rome, Italy",    
          "Madrid, Spain",    
          "Mexico City, Mexico",    
          "Shanghai, China",    
          "Rio de Janeiro, Brazil",    
          "Los Angeles, United States",    
          "Buenos Aires, Argentina",    
          "Sydney, Australia",    
          "Johannesburg, South Africa"]

# API Endpoint for current weather data
weather_endpoint = f"http://api.openweathermap.org/data/2.5/weather?q={location}&appid={api_key}"

# Fetch current weather data
weather_data = requests.get(weather_endpoint).json()
print(weather_data)

{'coord': {'lon': 28.0436, 'lat': -26.2023}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 293.87, 'feels_like': 293.93, 'temp_min': 292.57, 'temp_max': 294.9, 'pressure': 1015, 'humidity': 74}, 'visibility': 10000, 'wind': {'speed': 2.24, 'deg': 320, 'gust': 2.68}, 'clouds': {'all': 77}, 'dt': 1676365124, 'sys': {'type': 2, 'id': 2005686, 'country': 'ZA', 'sunrise': 1676346714, 'sunset': 1676393542}, 'timezone': 7200, 'id': 993800, 'name': 'Johannesburg', 'cod': 200}

In [109]:
# Create a list to store the weather information for each city
weather_list = []

# Loop through the list of cities
for location in cities:
    # API Endpoint for 5 day forecast data
    forecast_endpoint = f"http://api.openweathermap.org/data/2.5/forecast?q={location}&appid={api_key}"

    # Fetch 5 day forecast data
    forecast_data = requests.get(forecast_endpoint).json()
    #print('**********************Forecast Data**********************')
    #print(forecast_data)

    # Loop through the 5 day forecast data to get the weather information for each day
    for i in range(0, 40):
        date = datetime.fromtimestamp(forecast_data["list"][i]["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        location = forecast_data["city"]["name"]
        min_temp = forecast_data["list"][i]["main"]["temp_min"]
        max_temp = forecast_data["list"][i]["main"]["temp_max"]
        wind_direction = forecast_data["list"][i]["wind"]["deg"]
        wind_speed = forecast_data["list"][i]["wind"]["speed"]
        humidity = forecast_data["list"][i]["main"]["humidity"]
        pressure = forecast_data["list"][i]["main"]["pressure"]
        cloud = forecast_data["list"][i]["clouds"]["all"]
        temperature = forecast_data["list"][i]["main"]["temp"]
        
        if "rain" in forecast_data["list"][i]:
          rain = 1
        else:
          rain = 0
        
        if i + 8 >= 40:
          tomorrow_rain = 0
        elif "rain" in forecast_data["list"][i + 8]:
          tomorrow_rain = 1
        else:
          tomorrow_rain = 0

        weather_dict = {
          "Date": date,
          "Location": location,
          "Min_Temperature (C)": min_temp - 273.15,
          "Max_Temperature (C)": max_temp - 273.15,
          "Wind_Direction (°)": wind_direction,
          "Wind_Speed (m/s)": wind_speed,
          "Humidity (%)": humidity,
          "Pressure (hPa)": pressure,
          "Cloud (%)": cloud,
          "Temperature (C)": temperature - 273.15,
          "Today_Rain": rain,
          "Tomorrow_Rain": tomorrow_rain
        }

        weather_list.append(weather_dict)

data = pd.DataFrame(weather_list)

In [110]:
data

,Date,Location,Min_Temperature (C),Max_Temperature (C),Wind_Direction (°),Wind_Speed (m/s),Humidity (%),Pressure (hPa),Cloud (%),Temperature (C),Today_Rain,Tomorrow_Rain
0,2023-02-14 12:00:00,London,6.25,10.85,204,1.87,82,1031,62,6.25,0,0
1,2023-02-14 15:00:00,London,9.64,12.49,195,2.16,65,1030,26,9.64,0,0
2,2023-02-14 18:00:00,London,8.94,8.94,168,1.82,71,1028,21,8.94,0,0
3,2023-02-14 21:00:00,London,7.18,7.18,164,1.47,70,1028,80,7.18,0,0
4,2023-02-15 00:00:00,London,6.20,6.20,159,1.39,67,1027,72,6.20,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
795,2023-02-18 21:00:00,Johannesburg,14.73,14.73,110,4.55,93,1013,100,14.73,1,0
796,2023-02-19 00:00:00,Johannesburg,13.56,13.56,113,5.58,93,1013,100,13.56,1,0
797,2023-02-19 03:00:00,Johannesburg,13.15,13.15,103,5.52,90,1013,100,13.15,1,0
798,2023-02-19 06:00:00,Johannesburg,13.27,13.27,111,5.20,85,1014,100,13.27,0,0
799,2023-02-19 09:00:00,Johannesburg,18.97,18.97,83,4.10,59,1012,100,18.97,0,0

#Data Description

Date: The date and time of the forecast in the format YYYY-MM-DD HH:MM:SS.

Location: The name of the city for which the forecast was made.

Min_Temperature: The minimum temperature forecasted for the day in Celsius (C).

Max_Temperature: The maximum temperature forecasted for the day in Celsius (C).

Wind_Direction: The direction from which the wind is blowing, in degrees (°). A value of 0° means the wind is blowing from the north, 90° means it is blowing from the east, 180° means it is blowing from the south, and 270° means it is blowing from the west.

Wind_Speed: The speed of the wind in meters per second (m/s).

Humidity: The percentage of relative humidity forecasted for the day.

Pressure: The atmospheric pressure forecasted for the day in hPa (hectopascals).

Cloud: The percentage of cloud cover forecasted for the day.

Temperature: The current temperature at the time of the forecast in Celsius (C).

Today_Rain: A binary variable indicating whether or not it will rain on the day of the forecast. A value of 1 indicates that it will rain, and 0 indicates that it will not.

Tomorrow_Rain: A binary variable indicating whether or not it will rain the day after the forecast. A value of 1 indicates that it will rain, and 0 indicates that it will not.

In [111]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 800 non-null    object
 1   Location             800 non-null    object
 2   Min_Temperature (C)  800 non-null    float64
 3   Max_Temperature (C)  800 non-null    float64
 4   Wind_Direction (°)   800 non-null    int64
 5   Wind_Speed (m/s)     800 non-null    float64
 6   Humidity (%)         800 non-null    int64
 7   Pressure (hPa)       800 non-null    int64
 8   Cloud (%)            800 non-null    int64
 9   Temperature (C)      800 non-null    float64
 10  Today_Rain           800 non-null    int64
 11  Tomorrow_Rain        800 non-null    int64
dtypes: float64(4), int64(6), object(2)
memory usage: 75.1+ KB

In [112]:
data.describe()

,Min_Temperature (C),Max_Temperature (C),Wind_Direction (°),Wind_Speed (m/s),Humidity (%),Pressure (hPa),Cloud (%),Temperature (C),Today_Rain,Tomorrow_Rain
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000,800.00000
mean,12.426500,12.510650,170.111250,3.349962,61.553750,1019.073750,59.011250,12.459313,0.13750,0.10875
std,10.063647,10.078441,108.535576,2.088682,22.180951,8.224833,40.556839,10.072651,0.34459,0.31152
min,-16.760000,-16.760000,1.000000,0.100000,7.000000,1000.000000,0.000000,-16.760000,0.00000,0.00000
25%,5.770000,5.847500,72.000000,1.770000,44.000000,1012.000000,10.750000,5.822500,0.00000,0.00000
50%,11.030000,11.105000,168.000000,2.815000,62.000000,1019.000000,72.000000,11.030000,0.00000,0.00000
75%,20.477500,20.477500,252.500000,4.570000,81.000000,1026.000000,100.000000,20.477500,0.00000,0.00000
max,36.870000,36.870000,360.000000,12.350000,100.000000,1036.000000,100.000000,36.870000,1.00000,1.00000

In [113]:
data

,Date,Location,Min_Temperature (C),Max_Temperature (C),Wind_Direction (°),Wind_Speed (m/s),Humidity (%),Pressure (hPa),Cloud (%),Temperature (C),Today_Rain,Tomorrow_Rain
0,2023-02-14 12:00:00,London,6.25,10.85,204,1.87,82,1031,62,6.25,0,0
1,2023-02-14 15:00:00,London,9.64,12.49,195,2.16,65,1030,26,9.64,0,0
2,2023-02-14 18:00:00,London,8.94,8.94,168,1.82,71,1028,21,8.94,0,0
3,2023-02-14 21:00:00,London,7.18,7.18,164,1.47,70,1028,80,7.18,0,0
4,2023-02-15 00:00:00,London,6.20,6.20,159,1.39,67,1027,72,6.20,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
795,2023-02-18 21:00:00,Johannesburg,14.73,14.73,110,4.55,93,1013,100,14.73,1,0
796,2023-02-19 00:00:00,Johannesburg,13.56,13.56,113,5.58,93,1013,100,13.56,1,0
797,2023-02-19 03:00:00,Johannesburg,13.15,13.15,103,5.52,90,1013,100,13.15,1,0
798,2023-02-19 06:00:00,Johannesburg,13.27,13.27,111,5.20,85,1014,100,13.27,0,0
799,2023-02-19 09:00:00,Johannesburg,18.97,18.97,83,4.10,59,1012,100,18.97,0,0

In [114]:
data.drop(columns='Date', inplace=True)

In [115]:
data

,Location,Min_Temperature (C),Max_Temperature (C),Wind_Direction (°),Wind_Speed (m/s),Humidity (%),Pressure (hPa),Cloud (%),Temperature (C),Today_Rain,Tomorrow_Rain
0,London,6.25,10.85,204,1.87,82,1031,62,6.25,0,0
1,London,9.64,12.49,195,2.16,65,1030,26,9.64,0,0
2,London,8.94,8.94,168,1.82,71,1028,21,8.94,0,0
3,London,7.18,7.18,164,1.47,70,1028,80,7.18,0,0
4,London,6.20,6.20,159,1.39,67,1027,72,6.20,0,0
...,...,...,...,...,...,...,...,...,...,...,...
795,Johannesburg,14.73,14.73,110,4.55,93,1013,100,14.73,1,0
796,Johannesburg,13.56,13.56,113,5.58,93,1013,100,13.56,1,0
797,Johannesburg,13.15,13.15,103,5.52,90,1013,100,13.15,1,0
798,Johannesburg,13.27,13.27,111,5.20,85,1014,100,13.27,0,0
799,Johannesburg,18.97,18.97,83,4.10,59,1012,100,18.97,0,0

In [116]:
data['Location'] = data['Location'].map({"London":0,    
                                        "Paris":1,    
                                        "New York":2,    
                                        "Tokyo":3,    
                                        "Beijing":4,    
                                        "Istanbul":5,    
                                        "Moscow":6,    
                                        "Berlin":7,    
                                        "Bangkok":8,    
                                        "Seoul":9,   
                                        "Mumbai":10,   
                                        "Rome":11,    
                                        "Madrid":12,    
                                        "Mexico City":13,    
                                        "Shanghai":14,    
                                        "Rio de Janeiro":15,    
                                        "Los Angeles":16,    
                                        "Buenos Aires":17,    
                                        "Sydney":18,    
                                        "Johannesburg":19})

In [117]:
data['Location'] = data['Location'].astype(int)
data

,Location,Min_Temperature (C),Max_Temperature (C),Wind_Direction (°),Wind_Speed (m/s),Humidity (%),Pressure (hPa),Cloud (%),Temperature (C),Today_Rain,Tomorrow_Rain
0,0,6.25,10.85,204,1.87,82,1031,62,6.25,0,0
1,0,9.64,12.49,195,2.16,65,1030,26,9.64,0,0
2,0,8.94,8.94,168,1.82,71,1028,21,8.94,0,0
3,0,7.18,7.18,164,1.47,70,1028,80,7.18,0,0
4,0,6.20,6.20,159,1.39,67,1027,72,6.20,0,0
...,...,...,...,...,...,...,...,...,...,...,...
795,19,14.73,14.73,110,4.55,93,1013,100,14.73,1,0
796,19,13.56,13.56,113,5.58,93,1013,100,13.56,1,0
797,19,13.15,13.15,103,5.52,90,1013,100,13.15,1,0
798,19,13.27,13.27,111,5.20,85,1014,100,13.27,0,0
799,19,18.97,18.97,83,4.10,59,1012,100,18.97,0,0

In [118]:
data['Tomorrow_Rain'].value_counts()

0    713
1     87
Name: Tomorrow_Rain, dtype: int64

In [119]:
x = data.drop('Tomorrow_Rain', axis=1)
y = data['Tomorrow_Rain']

In [120]:
x

,Location,Min_Temperature (C),Max_Temperature (C),Wind_Direction (°),Wind_Speed (m/s),Humidity (%),Pressure (hPa),Cloud (%),Temperature (C),Today_Rain
0,0,6.25,10.85,204,1.87,82,1031,62,6.25,0
1,0,9.64,12.49,195,2.16,65,1030,26,9.64,0
2,0,8.94,8.94,168,1.82,71,1028,21,8.94,0
3,0,7.18,7.18,164,1.47,70,1028,80,7.18,0
4,0,6.20,6.20,159,1.39,67,1027,72,6.20,0
...,...,...,...,...,...,...,...,...,...,...
795,19,14.73,14.73,110,4.55,93,1013,100,14.73,1
796,19,13.56,13.56,113,5.58,93,1013,100,13.56,1
797,19,13.15,13.15,103,5.52,90,1013,100,13.15,1
798,19,13.27,13.27,111,5.20,85,1014,100,13.27,0
799,19,18.97,18.97,83,4.10,59,1012,100,18.97,0

In [121]:
y

0      0
1      0
2      0
3      0
4      0
      ..
795    0
796    0
797    0
798    0
799    0
Name: Tomorrow_Rain, Length: 800, dtype: int64

In [122]:
from imblearn.over_sampling import SMOTE

oversample = SMOTE()

X_oversampled, y_oversampled = oversample.fit_resample(x, y)

df = pd.concat([pd.DataFrame(X_oversampled), pd.DataFrame(y_oversampled)], axis=1)

df

,Location,Min_Temperature (C),Max_Temperature (C),Wind_Direction (°),Wind_Speed (m/s),Humidity (%),Pressure (hPa),Cloud (%),Temperature (C),Today_Rain,Tomorrow_Rain
0,0,6.250000,10.850000,204,1.870000,82,1031,62,6.250000,0,0
1,0,9.640000,12.490000,195,2.160000,65,1030,26,9.640000,0,0
2,0,8.940000,8.940000,168,1.820000,71,1028,21,8.940000,0,0
3,0,7.180000,7.180000,164,1.470000,70,1028,80,7.180000,0,0
4,0,6.200000,6.200000,159,1.390000,67,1027,72,6.200000,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1421,15,25.975814,25.975814,331,1.895138,84,1006,98,25.975814,1,1
1422,16,26.473827,26.473827,108,2.019923,73,1005,72,26.473827,0,1
1423,15,26.057999,26.057999,348,1.965820,84,1008,73,26.057999,1,1
1424,19,15.107873,15.107873,77,1.889273,95,1009,100,15.107873,1,1
1425,7,4.004298,4.004298,235,2.672668,84,1022,100,4.004298,0,1

In [123]:
df['Tomorrow_Rain'].value_counts()

0    713
1    713
Name: Tomorrow_Rain, dtype: int64

In [124]:
X = df.drop('Tomorrow_Rain', axis=1)
Y = df['Tomorrow_Rain']

In [125]:
X

,Location,Min_Temperature (C),Max_Temperature (C),Wind_Direction (°),Wind_Speed (m/s),Humidity (%),Pressure (hPa),Cloud (%),Temperature (C),Today_Rain
0,0,6.250000,10.850000,204,1.870000,82,1031,62,6.250000,0
1,0,9.640000,12.490000,195,2.160000,65,1030,26,9.640000,0
2,0,8.940000,8.940000,168,1.820000,71,1028,21,8.940000,0
3,0,7.180000,7.180000,164,1.470000,70,1028,80,7.180000,0
4,0,6.200000,6.200000,159,1.390000,67,1027,72,6.200000,0
...,...,...,...,...,...,...,...,...,...,...
1421,15,25.975814,25.975814,331,1.895138,84,1006,98,25.975814,1
1422,16,26.473827,26.473827,108,2.019923,73,1005,72,26.473827,0
1423,15,26.057999,26.057999,348,1.965820,84,1008,73,26.057999,1
1424,19,15.107873,15.107873,77,1.889273,95,1009,100,15.107873,1
1425,7,4.004298,4.004298,235,2.672668,84,1022,100,4.004298,0

In [126]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
1421    1
1422    1
1423    1
1424    1
1425    1
Name: Tomorrow_Rain, Length: 1426, dtype: int64

In [127]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.25,random_state=143)

In [ ]:
!pip install pycaret

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pycaret
  Downloading pycaret-2.3.10-py3-none-any.whl (320 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.2/320.2 KB 7.0 MB/s eta 0:00:00
Requirement already satisfied: nltk in /usr/local/lib/python3.8/dist-packages (from pycaret) (3.7)
Collecting kmodes>=0.10.1
  Downloading kmodes-0.12.2-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: plotly>=4.4.1 in /usr/local/lib/python3.8/dist-packages (from pycaret) (5.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from pycaret) (1.3.5)
Collecting mlxtend>=0.17.0
  Downloading mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 37.4 MB/s eta 0:00:00
Collecting scipy<=1.5.4
  Downloading scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl (25.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 52.1 MB/s eta 0:00:00
Collecting scikit-plot
  Downloading scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Requirement already satisfied: IPython in /usr/local/lib/python3.8/dist-packages (from pycaret) (7.9.0)
Collecting spacy<2.4.0
  Downloading spacy-2.3.9-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 91.2 MB/s eta 0:00:00
Collecting pyLDAvis
  Downloading pyLDAvis-3.3.1.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 80.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.8/dist-packages (from pycaret) (7.7.1)
Requirement already satisfied: cufflinks>=0.17.0 in /usr/local/lib/python3.8/dist-packages (from pycaret) (0.17.3)
Collecting imbalanced-learn==0.7.0
  Downloading imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 KB 19.8 MB/s eta 0:00:00
Collecting umap-learn
  Downloading umap-learn-0.5.3.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 KB 11.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: gensim<4.0.0 in /usr/local/lib/python3.8/dist-packages (from pycaret) (3.6.0)
Collecting lightgbm>=2.3.1
  Downloading lightgbm-3.3.5-py3-none-manylinux1_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 79.3 MB/s eta 0:00:00
Collecting pandas-profiling>=2.8.0
  Downloading pandas_profiling-3.6.6-py2.py3-none-any.whl (324 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 KB 33.5 MB/s eta 0:00:00
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from pycaret) (1.2.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.8/dist-packages (from pycaret) (0.11.2)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.8/dist-packages (from pycaret) (1.8.2.2)
Requirement already satisfied: textblob in /usr/local/lib/python3.8/dist-packages (from pycaret) (0.15.3)
Collecting Boruta
  Downloading Boruta-0.3-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.6/56.6 KB 6.7 MB/s eta 0:00:00
Collecting mlflow
  Downloading mlflow-2.1.1-py3-none-any.whl (16.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 76.4 MB/s eta 0:00:00
Collecting pyyaml<6.0.0
  Downloading PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 662.4/662.4 KB 54.4 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from pycaret) (3.2.2)
Requirement already satisfied: yellowbrick>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from pycaret) (1.5)
Collecting pyod
  Downloading pyod-1.0.7.tar.gz (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.7/147.7 KB 11.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numba<0.55
  Downloading numba-0.54.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 86.2 MB/s eta 0:00:00
Collecting scikit-learn==0.23.2
  Downloading scikit_learn-0.23.2-cp38-cp38-manylinux1_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 60.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.8/dist-packages (from imbalanced-learn==0.7.0->pycaret) (1.21.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn==0.23.2->pycaret) (3.1.0)
Requirement already satisfied: setuptools>=34.4.1 in /usr/local/lib/python3.8/dist-packages (from cufflinks>=0.17.0->pycaret) (57.4.0)
Requirement already satisfied: colorlover>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from cufflinks>=0.17.0->pycaret) (0.3.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from cufflinks>=0.17.0->pycaret) (1.15.0)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.8/dist-packages (from gensim<4.0.0->pycaret) (6.3.0)
Collecting jedi>=0.10
  Downloading jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 54.9 MB/s eta 0:00:00
Requirement already satisfied: decorator in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (4.4.2)
Requirement already satisfied: pygments in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (2.6.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (4.8.0)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (2.0.10)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (0.2.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (5.7.1)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from ipywidgets->pycaret) (3.0.5)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.8/dist-packages (from ipywidgets->pycaret) (3.6.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.8/dist-packages (from ipywidgets->pycaret) (0.2.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.8/dist-packages (from ipywidgets->pycaret) (5.3.4)
Requirement already satisfied: wheel in /usr/local/lib/python3.8/dist-packages (from lightgbm>=2.3.1->pycaret) (0.38.4)
Collecting mlxtend>=0.17.0
  Downloading mlxtend-0.20.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 61.0 MB/s eta 0:00:00
  Downloading mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 54.2 MB/s eta 0:00:00
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->pycaret) (3.0.9)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->pycaret) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->pycaret) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->pycaret) (1.4.4)
Collecting numpy>=1.13.3
  Downloading numpy-1.20.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.4/15.4 MB 46.1 MB/s eta 0:00:00
Collecting llvmlite<0.38,>=0.37.0rc1
  Downloading llvmlite-0.37.0-cp38-cp38-manylinux2014_x86_64.whl (26.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.3/26.3 MB 13.2 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->pycaret) (2022.7.1)
Collecting ydata-profiling
  Downloading ydata_profiling-4.0.0-py2.py3-none-any.whl (344 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 344.5/344.5 KB 27.0 MB/s eta 0:00:00
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from plotly>=4.4.1->pycaret) (8.2.0)
Collecting thinc<7.5.0,>=7.4.1
  Downloading thinc-7.4.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 65.5 MB/s eta 0:00:00
Collecting srsly<1.1.0,>=1.0.2
  Downloading srsly-1.0.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (211 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 KB 25.1 MB/s eta 0:00:00
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (2.25.1)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (3.0.8)
Collecting plac<1.2.0,>=0.9.6
  Downloading plac-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (4.64.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (1.0.9)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (0.10.1)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (0.7.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (2.0.7)
Collecting catalogue<1.1.0,>=0.0.7
  Downloading catalogue-1.0.2-py2.py3-none-any.whl (16 kB)
Collecting yellowbrick>=1.0.1
  Downloading yellowbrick-1.4-py3-none-any.whl (274 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 274.2/274.2 KB 29.9 MB/s eta 0:00:00
  Downloading yellowbrick-1.3.post1-py3-none-any.whl (271 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 271.4/271.4 KB 30.9 MB/s eta 0:00:00
Collecting numpy>=1.13.3
  Downloading numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 57.3 MB/s eta 0:00:00
Requirement already satisfied: sqlalchemy<2,>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (1.4.46)
Collecting shap<1,>=0.40
  Downloading shap-0.41.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (575 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 575.9/575.9 KB 31.9 MB/s eta 0:00:00
Collecting gitpython<4,>=2.1.0
  Downloading GitPython-3.1.30-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.0/184.0 KB 21.2 MB/s eta 0:00:00
Collecting alembic<2
  Downloading alembic-1.9.3-py3-none-any.whl (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.6/210.6 KB 24.4 MB/s eta 0:00:00
Requirement already satisfied: cloudpickle<3 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (2.2.1)
Collecting docker<7,>=4.0.0
  Downloading docker-6.0.1-py3-none-any.whl (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.5/147.5 KB 17.8 MB/s eta 0:00:00
Requirement already satisfied: Jinja2<4,>=2.11 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (2.11.3)
Collecting importlib-metadata!=4.7.0,<6,>=3.7.0
  Downloading importlib_metadata-5.2.0-py3-none-any.whl (21 kB)
Requirement already satisfied: entrypoints<1 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (0.4)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (7.1.2)
Collecting databricks-cli<1,>=0.8.7
  Downloading databricks-cli-0.17.4.tar.gz (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.3/82.3 KB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyarrow<11,>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (9.0.0)
Collecting querystring-parser<2
  Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
Requirement already satisfied: protobuf<5,>=3.12.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (3.19.6)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (0.4.3)
Requirement already satisfied: markdown<4,>=3.3 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (3.4.1)
Collecting gunicorn<21
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 9.7 MB/s eta 0:00:00
Collecting packaging<23
  Downloading packaging-22.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 KB 3.5 MB/s eta 0:00:00
Requirement already satisfied: Flask<3 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (1.1.4)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk->pycaret) (2022.6.2)
Requirement already satisfied: future in /usr/local/lib/python3.8/dist-packages (from pyLDAvis->pycaret) (0.16.0)
Collecting sklearn
  Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
Collecting funcy
  Downloading funcy-1.18-py2.py3-none-any.whl (33 kB)
Collecting pyLDAvis
  Downloading pyLDAvis-3.3.0.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 36.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Downloading pyLDAvis-3.2.2.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 54.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numexpr in /usr/local/lib/python3.8/dist-packages (from pyLDAvis->pycaret) (2.8.4)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.8/dist-packages (from pyod->pycaret) (0.12.2)
Collecting pynndescent>=0.5
  Downloading pynndescent-0.5.8.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 58.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /usr/local/lib/python3.8/dist-packages (from wordcloud->pycaret) (7.1.2)
Collecting Mako
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 KB 8.8 MB/s eta 0:00:00
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.8/dist-packages (from alembic<2->mlflow->pycaret) (5.10.2)
Collecting pyjwt>=1.7.0
  Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
Requirement already satisfied: oauthlib>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret) (3.2.2)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.8/dist-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret) (0.8.10)
Collecting requests<3.0.0,>=2.13.0
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 3.4 MB/s eta 0:00:00
Collecting websocket-client>=0.32.0
  Downloading websocket_client-1.5.1-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 KB 6.7 MB/s eta 0:00:00
Collecting urllib3>=1.26.0
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 16.7 MB/s eta 0:00:00
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.8/dist-packages (from Flask<3->mlflow->pycaret) (1.0.1)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.8/dist-packages (from Flask<3->mlflow->pycaret) (1.1.0)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 KB 8.0 MB/s eta 0:00:00
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata!=4.7.0,<6,>=3.7.0->mlflow->pycaret) (3.12.1)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.8/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.0.4)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.8/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.1.12)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from jedi>=0.10->IPython->pycaret) (0.8.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/dist-packages (from Jinja2<4,>=2.11->mlflow->pycaret) (2.0.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->IPython->pycaret) (0.2.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.13.0->spacy<2.4.0->pycaret) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.13.0->spacy<2.4.0->pycaret) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.13.0->spacy<2.4.0->pycaret) (2.1.1)
Collecting slicer==0.0.7
  Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.8/dist-packages (from sqlalchemy<2,>=1.4.0->mlflow->pycaret) (2.0.2)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.8/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->pycaret) (5.7.16)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.8/dist-packages (from pexpect->IPython->pycaret) (0.7.0)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.8/dist-packages (from statsmodels->pyod->pycaret) (0.5.3)
Collecting multimethod<1.10,>=1.4
  Downloading multimethod-1.9.1-py3-none-any.whl (10 kB)
Collecting htmlmin==0.1.12
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1
  Downloading phik-0.12.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (679 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.5/679.5 KB 52.6 MB/s eta 0:00:00
Collecting statsmodels
  Downloading statsmodels-0.13.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 102.9 MB/s eta 0:00:00
Collecting typeguard<2.14,>=2.13.2
  Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Requirement already satisfied: pydantic<1.11,>=1.8.1 in /usr/local/lib/python3.8/dist-packages (from ydata-profiling->pandas-profiling>=2.8.0->pycaret) (1.10.4)
Collecting visions[type_image_path]==0.7.5
  Downloading visions-0.7.5-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 KB 13.2 MB/s eta 0:00:00
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.8/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling>=2.8.0->pycaret) (22.2.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.8/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling>=2.8.0->pycaret) (3.0)
Collecting tangled-up-in-unicode>=0.0.4
  Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 88.3 MB/s eta 0:00:00
Collecting imagehash
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 KB 31.9 MB/s eta 0:00:00
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)

In [128]:
from pycaret.classification import *
s = setup(data = df, target = 'Tomorrow_Rain', session_id=123)
best_model = compare_models()

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
et,Extra Trees Classifier,0.9249,0.9738,0.9377,0.9147,0.9252,0.8498,0.8517,0.342
rf,Random Forest Classifier,0.9208,0.9686,0.9476,0.9011,0.9229,0.8417,0.8446,0.271
lightgbm,Light Gradient Boosting Machine,0.9018,0.9626,0.9396,0.8747,0.9050,0.8037,0.8080,0.138
gbc,Gradient Boosting Classifier,0.8757,0.9343,0.9255,0.8453,0.8820,0.7517,0.7583,0.317
dt,Decision Tree Classifier,0.8707,0.8709,0.9012,0.8498,0.8740,0.7415,0.7444,0.018
knn,K Neighbors Classifier,0.8287,0.9122,0.9718,0.7554,0.8497,0.6580,0.6874,0.025
ada,Ada Boost Classifier,0.8246,0.8963,0.8568,0.8075,0.8290,0.6494,0.6550,0.201
lda,Linear Discriminant Analysis,0.7956,0.8567,0.8203,0.7823,0.7991,0.5911,0.5950,0.032
ridge,Ridge Classifier,0.7946,0.0000,0.8183,0.7820,0.7978,0.5891,0.5932,0.013
lr,Logistic Regression,0.7334,0.8061,0.7057,0.7461,0.7231,0.4667,0.4699,0.380
nb,Naive Bayes,0.7274,0.7926,0.7176,0.7311,0.7221,0.4547,0.4571,0.015
svm,SVM - Linear Kernel,0.5642,0.0000,0.5294,0.4898,0.4542,0.1258,0.1730,0.021
qda,Quadratic Discriminant Analysis,0.5600,0.5852,0.5981,0.4737,0.4824,0.1191,0.1385,0.029
dummy,Dummy Classifier,0.5030,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.017

INFO:logs:create_model_container: 14
INFO:logs:master_model_container: 14
INFO:logs:display_container: 2
INFO:logs:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=123, verbose=0,
                     warm_start=False)
INFO:logs:compare_models() succesfully completed......................................

In [129]:
model = create_model('et')
model

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.8800  0.9510  0.9000  0.8654  0.8824  0.7600  0.7606
1       0.8600  0.9478  0.8400  0.8750  0.8571  0.7200  0.7206
2       0.9400  0.9782  0.9400  0.9400  0.9400  0.8800  0.8800
3       0.9700  0.9976  1.0000  0.9434  0.9709  0.9400  0.9417
4       0.9500  0.9770  0.9400  0.9592  0.9495  0.9000  0.9002
5       0.9200  0.9626  0.9200  0.9200  0.9200  0.8400  0.8400
6       0.9300  0.9784  0.9796  0.8889  0.9320  0.8602  0.8645
7       0.9300  0.9784  0.9796  0.8889  0.9320  0.8602  0.8645
8       0.9293  0.9796  0.9796  0.8889  0.9320  0.8587  0.8631
9       0.9394  0.9871  0.8980  0.9778  0.9362  0.8787  0.8816
Mean    0.9249  0.9738  0.9377  0.9147  0.9252  0.8498  0.8517
Std     0.0307  0.0147  0.0469  0.0367  0.0311  0.0614  0.0618

INFO:logs:create_model_container: 15
INFO:logs:master_model_container: 15
INFO:logs:display_container: 3
INFO:logs:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=123, verbose=0,
                     warm_start=False)
INFO:logs:create_model() succesfully completed......................................

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=123, verbose=0,
                     warm_start=False)

In [130]:
model.fit(x_train, y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=123, verbose=0,
                     warm_start=False)

In [131]:
x_train_prediction = model.predict(x_train)
x_train_prediction

array([1, 0, 1, ..., 0, 0, 0])

In [132]:
x_test_prediction = model.predict(x_test)
x_test_prediction

array([1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1])

In [133]:
from sklearn.metrics import accuracy_score

training_data_accuracy = accuracy_score(x_train_prediction, y_train)

test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [134]:
print('Accuracy on Training data : ', training_data_accuracy)

print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy on Training data :  1.0
Accuracy score on Test Data :  0.927170868347339

In [135]:
print("Enter Climate Details to Predict it'll rain tomorrow or not")
print('-----------------------------------------------------------------')

a = int(input('''Location (London : 0, Paris : 1, New York : 2, Tokyo : 3, Beijing : 4,    
                             Istanbul : 5, Moscow : 6, Berlin : 7, Bangkok : 8, Seoul : 9,   
                             Mumbai : 10, Rome : 11, Madrid : 12, Mexico City : 13, Shanghai : 14,    
                             Rio de Janeiro : 15, Los Angeles : 16, Buenos Aires : 17,  Sydney : 18, Johannesburg : 19) : '''))
b = float(input("Min_Temperature (C) : "))
c = float(input("Max_Temperature (C) : "))
d = int(input("Wind_Direction () 0° - blowing from the north, 90° - blowing from the east, 180° - blowing from the south, 270° - blowing from the west) : "))
e = float(input("Wind_Speed (m/s) : "))
f = int(input("Humidity (%) : "))
g = int(input("Pressure (hPa) : "))
h = int(input("Cloud (%) : "))
i = float(input("Temperature (C) : "))
j = int(input('Today Rain (0 - No, 1 - Yes) : '))

features = np.array([[a, b, c, d, e, f, g, h, i, j]])

prediction = model.predict(features)
print(prediction)

if (prediction[0]==1):
  print("Yes, it'll rain tomorrow")
else:
  print("No, it'll not rain tomorrow")

Enter Climate Details to Predict it'll rain tomorrow or not
-----------------------------------------------------------------
Location (London : 0, Paris : 1, New York : 2, Tokyo : 3, Beijing : 4,
                             Istanbul : 5, Moscow : 6, Berlin : 7, Bangkok : 8, Seoul : 9,
                             Mumbai : 10, Rome : 11, Madrid : 12, Mexico City : 13, Shanghai : 14,
                             Rio de Janeiro : 15, Los Angeles : 16, Buenos Aires : 17,  Sydney : 18, Johannesburg : 19) : 0
Min_Temperature (C) : 6.25
Max_Temperature (C) : 10.85
Wind_Direction () 0° - blowing from the north, 90° - blowing from the east, 180° - blowing from the south, 270° - blowing from the west) : 204
Wind_Speed (m/s) : 1.87
Humidity (%) : 82
Pressure (hPa) : 1031
Cloud (%) : 62
Temperature (C) : 6.25
Today Rain (0 - No, 1 - Yes) : 0
[0]
No, it'll not rain tomorrow

In [139]:
print("Enter Climate Details to Predict it'll rain tomorrow or not")
print('-----------------------------------------------------------------')

a = int(input('''Location (London : 0, Paris : 1, New York : 2, Tokyo : 3, Beijing : 4,    
                             Istanbul : 5, Moscow : 6, Berlin : 7, Bangkok : 8, Seoul : 9,   
                             Mumbai : 10, Rome : 11, Madrid : 12, Mexico City : 13, Shanghai : 14,    
                             Rio de Janeiro : 15, Los Angeles : 16, Buenos Aires : 17,  Sydney : 18, Johannesburg : 19) : '''))
b = float(input("Min_Temperature (C) : "))
c = float(input("Max_Temperature (C) : "))
d = int(input("Wind_Direction () 0° - blowing from the north, 90° - blowing from the east, 180° - blowing from the south, 270° - blowing from the west) : "))
e = float(input("Wind_Speed (m/s) : "))
f = int(input("Humidity (%) : "))
g = int(input("Pressure (hPa) : "))
h = int(input("Cloud (%) : "))
i = float(input("Temperature (C) : "))
j = int(input('Today Rain (0 - No, 1 - Yes) : '))

features = np.array([[a, b, c, d, e, f, g, h, i, j]])

prediction = model.predict(features)
print(prediction)

if (prediction[0]==1):
  print("Yes, it'll rain tomorrow")
else:
  print("No, it'll not rain tomorrow")

Enter Climate Details to Predict it'll rain tomorrow or not
-----------------------------------------------------------------
Location (London : 0, Paris : 1, New York : 2, Tokyo : 3, Beijing : 4,
                             Istanbul : 5, Moscow : 6, Berlin : 7, Bangkok : 8, Seoul : 9,
                             Mumbai : 10, Rome : 11, Madrid : 12, Mexico City : 13, Shanghai : 14,
                             Rio de Janeiro : 15, Los Angeles : 16, Buenos Aires : 17,  Sydney : 18, Johannesburg : 19) : 15
Min_Temperature (C) : 25.97
Max_Temperature (C) : 25.97
Wind_Direction () 0° - blowing from the north, 90° - blowing from the east, 180° - blowing from the south, 270° - blowing from the west) : 331
Wind_Speed (m/s) : 1.895
Humidity (%) : 84
Pressure (hPa) : 1006
Cloud (%) : 98
Temperature (C) : 25.97
Today Rain (0 - No, 1 - Yes) : 1
[1]
Yes, it'll rain tomorrow

In [140]:
import pickle

with open('rain_prediction_model.pkl', 'wb') as file:
    pickle.dump(model, file)